### ISSUE TITLE
我想问一下webview_flutter

### ISSUE THREAD

**Issue by sing1** [woyehaizaixiang/DsBridgeWebview#1]
Error: MissingPluginException(No implementation found for method close on channel flutter_webview_plugin)
    at Object.throw_ [as throw] (http://localhost:54282/dart_sdk.js:5080:11)
    at MethodChannel._invokeMethod (http://localhost:54282/packages/flutter/src/services/restoration.dart.lib.js:1567:21)
    at _invokeMethod.next (<anonymous>)
    at http://localhost:54282/dart_sdk.js:40641:33
    at _RootZone.runUnary (http://localhost:54282/dart_sdk.js:40511:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:54282/dart_sdk.js:35438:29)
。。。。。。。
我想问一下你引用的插件webview_flutter都不支持web和macOs，你的插件能支持吗？？？

**Comment by woyehaizaixiang** [comment]
> Error: MissingPluginException(No implementation found for method close on channel flutter_webview_plugin)
> at Object.throw_ [as throw] (http://localhost:54282/dart_sdk.js:5080:11)
> at MethodChannel._invokeMethod (http://localhost:54282/packages/flutter/src/services/restoration.dart.lib.js:1567:21)
> at _invokeMethod.next ()
> at http://localhost:54282/dart_sdk.js:40641:33
> at _RootZone.runUnary (http://localhost:54282/dart_sdk.js:40511:59)
> at _FutureListener.thenAwait.handleValue (http://localhost:54282/dart_sdk.js:35438:29)
> 。。。。。。。
> 我想问一下你引用的插件webview_flutter都不支持web和macOs，你的插件能支持吗？？？

你想问的是webview_flutter插件支持web和桌面端吗

**Comment by woyehaizaixiang** [comment]
> 

webview_flutter目前只支持Android和iOS

**Comment by woyehaizaixiang** [comment]
> > Error: MissingPluginException(No implementation found for method close on channel flutter_webview_plugin)
> > at Object.throw_ [as throw] (http://localhost:54282/dart_sdk.js:5080:11)
> > at MethodChannel._invokeMethod (http://localhost:54282/packages/flutter/src/services/restoration.dart.lib.js:1567:21)
> > at _invokeMethod.next ()
> > at http://localhost:54282/dart_sdk.js:40641:33
> > at _RootZone.runUnary (http://localhost:54282/dart_sdk.js:40511:59)
> > at _FutureListener.thenAwait.handleValue (http://localhost:54282/dart_sdk.js:35438:29)
> > 。。。。。。。
> > 我想问一下你引用的插件webview_flutter都不支持web和macOs，你的插件能支持吗？？？
> 
> 你想问的是webview_flutter插件支持web和桌面端吗

webview_flutter插件目前只支持Android和iOS

**Comment by sing1** [comment]
> > > Error: MissingPluginException(No implementation found for method close on channel flutter_webview_plugin)
> > > at Object.throw_ [as throw] (http://localhost:54282/dart_sdk.js:5080:11)
> > > at MethodChannel._invokeMethod (http://localhost:54282/packages/flutter/src/services/restoration.dart.lib.js:1567:21)
> > > at _invokeMethod.next ()
> > > at http://localhost:54282/dart_sdk.js:40641:33
> > > at _RootZone.runUnary (http://localhost:54282/dart_sdk.js:40511:59)
> > > at _FutureListener.thenAwait.handleValue (http://localhost:54282/dart_sdk.js:35438:29)
> > > 。。。。。。。
> > > 我想问一下你引用的插件webview_flutter都不支持web和macOs，你的插件能支持吗？？？
> > 
> > 
> > 你想问的是webview_flutter插件支持web和桌面端吗
> 
> webview_flutter插件目前只支持Android和iOS

但是我在pub.dev中看到你的插件竟然支持web和桌面端，这就很灵性了
